# Generated by Django 4.1.4 on 2022-12-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlipayMyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Partner_transaction_id",
                    models.CharField(
                        max_length=100, verbose_name="Partner_transaction_id"
                    ),
                ),
                (
                    "Transaction_id",
                    models.CharField(max_length=100, verbose_name="Transaction_id"),
                ),
                ("Amount", models.IntegerField(max_length=50, verbose_name="Amount")),
                (
                    "Rmb_amount",
                    models.IntegerField(max_length=50, verbose_name="Rmb_amount"),
                ),
                ("Fee", models.IntegerField(max_length=50, verbose_name="Fee")),
                ("Refund", models.IntegerField(max_length=50, verbose_name="Refund")),
                (
                    "Settlement",
                    models.IntegerField(max_length=50, verbose_name="Settlement"),
                ),
                (
                    "Rmb_settlement",
                    models.IntegerField(max_length=50, verbose_name="Rmb_settlement"),
                ),
                ("Currency", models.CharField(max_length=100, verbose_name="Currency")),
                ("Rate", models.CharField(max_length=100, verbose_name="Rate")),
                (
                    "Payment_time",
                    models.DateTimeField(max_length=100, verbose_name="Payment_time"),
                ),
                (
                    "Settlement_time",
                    models.DateTimeField(
                        max_length=100, verbose_name="Settlement_time"
                    ),
                ),
                ("Type", models.CharField(max_length=100, verbose_name="Type")),
            ],
        ),
    ]
