# Generated by Django 4.1.4 on 2022-12-23 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ordersystem", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alipaymytransaction",
            options={"managed": True},
        ),
        migrations.AlterModelTable(
            name="alipaymytransaction",
            table="ordersystem_AlipayMyTransaction",
        ),
    ]
