# Generated by Django 4.1.4 on 2022-12-23 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ordersystem", "0002_alter_alipaymytransaction_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="alipaymytransaction",
            table="ordersys",
        ),
    ]
