# Generated by Django 4.1.4 on 2022-12-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordersystem", "0003_alter_alipaymytransaction_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alipaymytransaction",
            name="Amount",
            field=models.IntegerField(verbose_name="Amount"),
        ),
        migrations.AlterField(
            model_name="alipaymytransaction",
            name="Fee",
            field=models.IntegerField(verbose_name="Fee"),
        ),
        migrations.AlterField(
            model_name="alipaymytransaction",
            name="Refund",
            field=models.IntegerField(verbose_name="Refund"),
        ),
        migrations.AlterField(
            model_name="alipaymytransaction",
            name="Rmb_amount",
            field=models.IntegerField(verbose_name="Rmb_amount"),
        ),
        migrations.AlterField(
            model_name="alipaymytransaction",
            name="Rmb_settlement",
            field=models.IntegerField(verbose_name="Rmb_settlement"),
        ),
        migrations.AlterField(
            model_name="alipaymytransaction",
            name="Settlement",
            field=models.IntegerField(verbose_name="Settlement"),
        ),
    ]
