# Generated by Django 4.1.4 on 2022-12-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordersystem", "0005_alter_alipaymytransaction_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="TmgList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Order_id", models.CharField(max_length=100, verbose_name="Order_id")),
                (
                    "Transaction_id",
                    models.CharField(max_length=100, verbose_name="Transaction_id"),
                ),
                ("Order_time", models.DateTimeField(verbose_name="Order_time")),
                ("Pay_time", models.DateTimeField(verbose_name="Pay_time")),
                ("Send_time", models.DateTimeField(verbose_name="Send_time")),
                ("Confirm_time", models.DateTimeField(verbose_name="Confirm_time")),
            ],
            options={
                "db_table": "TmgOrder",
                "managed": True,
            },
        ),
        migrations.AlterModelTable(
            name="alipaymytransaction",
            table="AlipayOrder",
        ),
    ]
